SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
    VL_SALARIO NUMBER(10, 2) := &SALARIO;
    VL_SALARIOLIQUIDO NUMBER(10, 2);
BEGIN
    IF VL_SALARIO > 1513.79 AND VL_SALARIO <= 2725.12 THEN 
        VL_SALARIOLIQUIDO := VL_SALARIO - (VL_SALARIO * 16/100);
    ELSIF VL_SALARIO > 2725.12 THEN
        VL_SALARIOLIQUIDO := VL_SALARIO - (VL_SALARIO * 18/100);
    ELSE 
        VL_SALARIOLIQUIDO := VL_SALARIO;
    END IF;
    DBMS_OUTPUT.PUT_LINE('SALARIO LIQUIDO: ' || VL_SALARIOLIQUIDO);
END;



CREATE TABLE ALUNO(RA NUMBER(5) PRIMARY KEY, NOME VARCHAR2(50), NOTA NUMBER(5, 2), MEDIA NUMBER (5, 2), SITUACAO VARCHAR2(10));
--DROP TABLE ALUNO;

BEGIN
    INSERT INTO ALUNO VALUES(54321, 'VITORIA PESANHA', 10, NULL, NULL);
    INSERT INTO ALUNO VALUES(56789, 'GABRIEL SANTOS', 5, NULL, NULL);
    INSERT INTO ALUNO VALUES(98765, 'MATHEUS RAMOS', 8, NULL, NULL);
END;

DECLARE
    V_RA NUMBER (5) := &RA;
    VL_NOTA NUMBER(5, 2);
    V_SITUACAO VARCHAR2(30);
BEGIN
    SELECT NOTA into VL_NOTA FROM ALUNO WHERE RA = V_RA;
    IF vl_nota > 6 THEN
        V_SITUACAO := 'APROVADO';
    ELSE V_SITUACAO := 'REPROVADO';
    END IF;
    DBMS_OUTPUT.PUT_LINE('SITUAÇÃO: ' || v_situacao);
        
    UPDATE ALUNO SET MEDIA = VL_NOTA, SITUACAO = V_SITUACAO WHERE ra = v_ra;
    COMMIT;
END;

     
    
